name: Build & Release

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          modrinth-id: 6zYtBRSV
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          loaders: |
            bukkit
            spigot
            paper
            purpur
            folia
          game-versions: ">=1.8"
          game-version-filter: releases
          files: |
            target/topper-*-shaded.jar
            target/topper-*-@(sources|javadoc).jar
          name: ${{ github.ref_name }}
          version: ${{ github.ref_name }}